[tool.poetry]
name = "authfit"
version = "0.2.5"
description = "A basic workout tracking application."
authors = ["Marcus T Taylor <mtaylor9754@hotmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
]
packages = [{include = "authfit"}]

[tool.poetry.dependencies]
python = "^3.9"
customtkinter = "^5.2.1"
sqlalchemy = "^2.0.23"

[tool.poetry.scripts]
authfit-create='authfit.mockup.create:main'
authfit-delete='authfit.mockup.delete:main'
authfit-gui='authfit.gui:main'
authfit-read='authfit.mockup.read:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
