[tool.poetry]
name = "authenticity"
version = "0.2.6"
description = "A basic workout tracking application."
authors = ["Marcus T Taylor <mtaylor9754@hotmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
]
packages = [{include = "authenticity"}]

[tool.poetry.dependencies]
python = "^3.9"
customtkinter = "^5.2.1"
sqlalchemy = "^2.0.23"

[tool.poetry.scripts]
af-create='authenticity.mockup:create_workouts'
af-delete='authenticity.mockup:delete_workouts'
af-gui='authenticity.gui:main'
af-read='authenticity.mockup:read_workouts'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
