"""
exercises.py
Author:     Marcus T Taylor
Created:    11.10.24
Modified:   12.10.24
"""

exercise_list = {
    "Chest": [
        "Around The World",
        "Bridge Press",
        "Decline Bench Press",
        "Deficit Pushup",
        "Dumbbell Pullover",
        "Dumbbell Squeeze Press",
        "Dumbbell Svend Press",
        "Flat Bench Press",
        "Flat Dumbbell Fly",
        "Floor Press",
        "Incline Bench Press",
        "Incline Close Grip DB Press",
        "Incline Dumbbell Fly",
        "Standing Upward Fly",
        "Underhand Grip Chest Press",
    ],
    "Quads": [
        "Bulgarian Split Squat",
        "Curtsy Squat",
        "Forward Lunges",
        "Goblet Squat",
        "Leg Extension",
        "Pop Squat",
        "Reverse Lunges",
        "Sumo Squat",
        "Step-up",
    ],
    "Hamstrings": [
        "DB Good Morning",
        "DB Hamstring Bridge",
        "Hamstring March",
        "Lying Leg Curl",
        "Romanian Deadlift",
        "Single-Leg Deadlift",
        "Stiff-Legged Deadlift",
    ],
    "Glutes": [
        "DB Donkey Kicks",
        "Dumbbell Glute Bridges",
        "Dumbbell Hip Thrust",
        "Frog Pump",
        "Leaning Forward Step-up",
    ],
    "Calves": [
        "Dumbbell Farmer’s Walk on Toes",
        "Leaning Single-Leg Calf Raises",
        "Seated Dumbbell Calf Raises",
        "Standing Dumbbell Calf Raises",
    ],
    "Back": [
        "Bent-Over Row Overhand Grip",
        "Chest-Supported Incline Row",
        "Dumbbell Deadlift",
        "Dumbbell Pendley Row",
        "Dumbbell Renegade Row",
        "Dumbbell Seal Row",
        "Dumbbell Wide Row",
        "Incline I-Y-T Raises",
        "Incline Plank Row",
        "One Arm Dumbbell Row",
        "Underhand Inverted Row",
    ],
    "Shoulder": [
        "Alternating Front Raises",
        "Arnold Press",
        "Bent-over Lateral Raises",
        "Chest Supported Rear Delt Row",
        "Dumbbell Face Pull",
        "Dumbbell Lateral Raises",
        "Dumbbell Shrug",
        "Overhead Press",
        "Push Press",
        "Seated/Incline Y Raises",
        "Upright Row",
    ],
    "Bicep": [
        "Alternating Curls",
        "Concentration Curl",
        "Dumbbell Crossbody Curl",
        "Dumbbell Drag Curl",
        "Dumbbell Hammer Curl",
        "Dumbbell Preacher Curl",
        "Dumbbell Reverse Curl",
        "Dumbbell Zottoman Curl",
        "Incline Dumbbell Bicep Curl",
        "Incline Prone Bicep Curl",
        "Preacher Hammer Curl",
        "Single-arm Hammer Curl",
    ],
    "Core": [
        "Bird-Dog Plank",
        "Decline Dumbbell Crunches",
        "Dumbbell Plank Drag",
        "Dumbbell Plank Rowing",
        "Hanging Knee Raises",
        "Leg Raises",
        "Oblique crunches",
        "Reverse Crunches",
        "Russian Twist",
        "Side Plank",
        "Side Plank Hip Lifts",
        "Side-plank Rotation",
        "Standing Oblique Rotation",
        "Straight-Arm Crunches",
        "Toe Touch Crunches",
        "Wood Chop (High to Low)",
        "Wood Chop (Low to High)",
    ],
}
# https://thefitnessphantom.com/list-of-dumbbell-exercises
